### ISSUE TITLE
Any updates?

### ISSUE THREAD

**Issue by fuyunmanbu** [ClaudeChey/lat_compass#2]
Do you have any updates, Android seems to have packaging issues, need to update to adapt to higher versions! You can check it out. Thank you.

**Comment by hanolee** [comment]
@ClaudeChey Me Too. There are some issue for packaging.

<img width="1372" alt="스크린샷 2024-10-15 오전 1 16 15" src="https://github.com/user-attachments/assets/38170e2b-430e-4a50-8736-0b0a488f88ea">

**Comment by ClaudeChey** [comment]
@fuyunmanbu @hanolee fixed it
